[package]
name = "sample-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
typedb-driver = { version = "2.26.1", features = ["sync"] }
