[package]
name = "sync-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.111"
typedb-driver = { version = "2.26.5", features = ["sync"] }
